import React from 'react'
import type { Metadata } from 'next'
import { AIPopup, Navbar } from '@/components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased bg-background`}>
        <Navbar />
        {children}
        <AIPopup />
      </body>
    </html>
  )
}
