import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Navbar, NotificationSnackBar } from '@/components'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased bg-background`}>
        <NotificationSnackBar />
        {children}
      </body>
    </html>
  )
}
